#!/usr/bin/env bash
# Script transfers files from client to server
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# If less than 3 parameters transfer to ~/

PATH_TO_FILE=$1;
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ "$#" -lt 3 ]; then
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1

fi

if [ "$#" -eq 4 ]; then
scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
exit 0

fi

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"