#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and: displays bad luck for the 4th loop iteration; displays good luck for the 8th loop iteration; displays Best School for the other iterations

msg="Best School"
cnt=1
while [ $cnt -le 10 ];
do
    if [ $cnt == 4 ]; then
	echo "bad luck"
    elif [ $cnt == 8 ]; then
	echo "good luck"
    else
	echo "$msg"
    fi
    cnt=$((cnt + 1))
done
