#!/usr/bin/env bash
# Bash script that displays: (1) The dir_content of the current directory (2) In a command format (3) Where only the part of the name after the first dash is displayed

for file in *; do
	echo -e "$file" | cut -d "-" -f2
done 
