#!/usr/bin/env bash
# Configure ufw to block all incoming trafic
# but TCP pot 20, 80, & 443

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status verbose